sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm ganache
  - npm test
  - npm run coverage && cat coverage/lcov.info | coveralls